-- ==============================================
-- DevSynt AutoGram Engine - Database Schema
-- Execute this in Supabase SQL Editor
-- ==============================================

-- Main tracking table for posted images
CREATE TABLE posted_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id TEXT UNIQUE NOT NULL,
    filename TEXT NOT NULL,
    md5_hash TEXT,
    file_size INTEGER DEFAULT 0,
    image_url TEXT,
    storage_path TEXT,
    caption TEXT,
    hashtags TEXT[] DEFAULT '{}',
    ai_model_used TEXT DEFAULT 'gpt-4-vision-preview',
    ig_post_id TEXT,
    ig_media_id TEXT,
    status TEXT DEFAULT 'published',
    posted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Error logs table
CREATE TABLE error_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id TEXT,
    error_stage TEXT NOT NULL,
    error_message TEXT NOT NULL,
    error_stack TEXT,
    resolved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    resolved_at TIMESTAMP WITH TIME ZONE
);

-- Create indexes for performance
CREATE INDEX idx_posted_images_file_id ON posted_images(file_id);
CREATE INDEX idx_posted_images_posted_at ON posted_images(posted_at DESC);
CREATE INDEX idx_error_logs_created_at ON error_logs(created_at DESC);

-- Create trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_posted_images_updated_at 
    BEFORE UPDATE ON posted_images 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- View for daily summary
CREATE VIEW daily_post_summary AS
SELECT 
    DATE(posted_at) as post_date,
    COUNT(*) as total_posts,
    COUNT(CASE WHEN status = 'published' THEN 1 END) as successful_posts,
    COUNT(CASE WHEN status = 'failed' THEN 1 END) as failed_posts
FROM posted_images
WHERE posted_at >= NOW() - INTERVAL '30 days'
GROUP BY DATE(posted_at)
ORDER BY post_date DESC;

-- Analytics function for post stats
CREATE OR REPLACE FUNCTION get_post_statistics(days INTEGER DEFAULT 7)
RETURNS TABLE(
    total_posts BIGINT,
    avg_caption_length NUMERIC,
    avg_hashtag_count NUMERIC
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COUNT(*)::BIGINT as total_posts,
        ROUND(AVG(LENGTH(caption)), 2) as avg_caption_length,
        ROUND(AVG(ARRAY_LENGTH(hashtags, 1)), 2) as avg_hashtag_count
    FROM posted_images
    WHERE posted_at >= NOW() - (days || ' days')::INTERVAL
    AND status = 'published';
END;
$$ LANGUAGE plpgsql;